### ISSUE TITLE
Links point to https://nemo.github.io/stripe-f/?payment_success=true after checking out

### ISSUE THREAD

**Issue by codeluggage** [nemo/stripe-f#1]
I clicked through to test the payment, and after the redirect, the links at the top of the page were all pointing back to the same page but with payment_success=true.

**Comment by nemo** [comment]
@codeluggage yes, that's expected behavior. At that point, you can listen for payment_success and show a decent message for the user. The page that it redirects to can be set to anything (it just happens to be the same page in the example page).
